name: whispercppapp
description: Speech-to-Text application powered by whisper.cpp
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cross_file: ^0.3.3+2
  desktop_drop: ^0.4.0
  path_provider: ^2.0.11
  file_selector: ^0.9.2+2
  shared_preferences: ^2.0.15
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - exe/ffmpeg
    - exe/whispercpp
